//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 阅读笔记
    /// </summary>
    public partial class BookNote
    {
        /// <summary>
        /// 获取或设置阅读笔记编号
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 获取或设置图书编号
        /// </summary>
        public int BookID { get; set; }
        /// <summary>
        /// 获取或设置标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 获取或设置笔记内容
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// 获取或设置阅读开始时间
        /// </summary>
        public Nullable<System.DateTime> BeginTime { get; set; }
        /// <summary>
        /// 获取或设置阅读结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 获取或设置创建人编号
        /// </summary>
        public int CreateUserID { get; set; }
        /// <summary>
        /// 获取或设置最后修改时间
        /// </summary>
        public System.DateTime LastModifyTime { get; set; }
        /// <summary>
        /// 获取或设置最后修改人编号
        /// </summary>
        public int LastModifyUserID { get; set; }
        /// <summary>
        /// 获取或设置是否已删除
        /// </summary>
        public bool IsDelete { get; set; }
    
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual Book Book { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User CreateUser { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User LastModifyUser { get; set; }
    }
}
