//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 借阅人
    /// </summary>
    public partial class Borrower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrower()
        {
            this.BorrowRecords = new HashSet<BorrowRecord>();
        }
    
        /// <summary>
        /// 获取或设置借阅人编号
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 获取或设置借阅人姓名
        /// </summary>
        public string BorrowerName { get; set; }
        /// <summary>
        /// 获取或设置借阅人性别
        /// </summary>
        public Nullable<byte> Gender { get; set; }
        /// <summary>
        /// 获取或设置电话
        /// </summary>
        public string Cellphone { get; set; }
        /// <summary>
        /// 获取或设置邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 获取或设置关系
        /// </summary>
        public string Relationship { get; set; }
        /// <summary>
        /// 获取或设置信用记录
        /// </summary>
        public Nullable<byte> Record { get; set; }
        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 获取或设置创建人编号
        /// </summary>
        public int CreateUserID { get; set; }
        /// <summary>
        /// 获取或设置最后修改时间
        /// </summary>
        public System.DateTime LastModifyTime { get; set; }
        /// <summary>
        /// 获取或设置最后修改人编号
        /// </summary>
        public int LastModifyUserID { get; set; }
        /// <summary>
        /// 获取或设置是否已删除
        /// </summary>
        public bool IsDelete { get; set; }
    
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User CreateUser { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User LastModifyUser { get; set; }
        /// <summary>
    	
    	/// 获取或设置借阅记录
        
    	/// </summary>
        public virtual ICollection<BorrowRecord> BorrowRecords { get; set; }
    }
}
