//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Books = new HashSet<Book>();
            this.Books1 = new HashSet<Book>();
            this.BookCategories = new HashSet<BookCategory>();
            this.BookCategories1 = new HashSet<BookCategory>();
            this.BookNotes = new HashSet<BookNote>();
            this.BookNotes1 = new HashSet<BookNote>();
            this.Borrowers = new HashSet<Borrower>();
            this.Borrowers1 = new HashSet<Borrower>();
            this.BorrowRecords = new HashSet<BorrowRecord>();
            this.BorrowRecords1 = new HashSet<BorrowRecord>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
        }
    
        /// <summary>
        /// 获取或设置用户编号
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 获取或设置登录名
        /// </summary>
        public string Account { get; set; }
        /// <summary>
        /// 获取或设置用户姓名
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 获取或设置密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 获取或设置最后一次访问时间
        /// </summary>
        public Nullable<System.DateTime> LastVisitTime { get; set; }
        /// <summary>
        /// 获取或设置创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 获取或设置创建人编号
        /// </summary>
        public Nullable<int> CreateUserID { get; set; }
        /// <summary>
        /// 获取或设置最后修改时间
        /// </summary>
        public System.DateTime LastModifyTime { get; set; }
        /// <summary>
        /// 获取或设置最后修改人编号
        /// </summary>
        public Nullable<int> LastModifyUserID { get; set; }
        /// <summary>
        /// 获取或设置是否已删除
        /// </summary>
        public bool IsDelete { get; set; }
    
        /// <summary>
    	
    	/// 获取或设置图书信息
        
    	/// </summary>
        public virtual ICollection<Book> Books { get; set; }
        /// <summary>
    	
    	/// 获取或设置图书信息
        
    	/// </summary>
        public virtual ICollection<Book> Books1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置图书分类
        
    	/// </summary>
        public virtual ICollection<BookCategory> BookCategories { get; set; }
        /// <summary>
    	
    	/// 获取或设置图书分类
        
    	/// </summary>
        public virtual ICollection<BookCategory> BookCategories1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置阅读笔记
        
    	/// </summary>
        public virtual ICollection<BookNote> BookNotes { get; set; }
        /// <summary>
    	
    	/// 获取或设置阅读笔记
        
    	/// </summary>
        public virtual ICollection<BookNote> BookNotes1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置借阅人
        
    	/// </summary>
        public virtual ICollection<Borrower> Borrowers { get; set; }
        /// <summary>
    	
    	/// 获取或设置借阅人
        
    	/// </summary>
        public virtual ICollection<Borrower> Borrowers1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置借阅记录
        
    	/// </summary>
        public virtual ICollection<BorrowRecord> BorrowRecords { get; set; }
        /// <summary>
    	
    	/// 获取或设置借阅记录
        
    	/// </summary>
        public virtual ICollection<BorrowRecord> BorrowRecords1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual ICollection<User> User1 { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User CreateUser { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual ICollection<User> User11 { get; set; }
        /// <summary>
    	
    	/// 获取或设置
        
    	/// </summary>
        public virtual User LastModifyUser { get; set; }
    }
}
